name: Build CV

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Typst
        uses: typst-community/setup-typst@v4

      - name: Compile CV
        run: typst compile cv.typ OscarWeimannCV.pdf

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: OscarWeimannCV
          path: OscarWeimannCV.pdf

      - name: Publish to Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: latest
          files: OscarWeimannCV.pdf
          make_latest: true
